title: Stripe
technology_logo:
  - images/projects/technology_logos/stripe.svg
updated_by: d5ab20b3-388d-4650-bb43-d170de415ebf
updated_at: 1709679504
blueprint: technology
headline: 'Stripe API deveopers'
sub_headline: "We've gone deep with the Stripe API on just about all of our products."
content:
  -
    type: paragraph
    content:
      -
        type: text
        marks:
          -
            type: link
            attrs:
              href: 'https://stripe.com'
              rel: null
              target: null
              title: null
        text: Stripe
      -
        type: text
        text: " has been our obvious go-to when it comes to subscription billing for the SaaS products we've built.  "
  -
    type: paragraph
    content:
      -
        type: text
        text: "And on that end, we've built all of the common iterations of SaaS subscription billing with Stripe:"
  -
    type: bulletList
    content:
      -
        type: listItem
        content:
          -
            type: paragraph
            content:
              -
                type: text
                text: 'Free trial to plans'
      -
        type: listItem
        content:
          -
            type: paragraph
            content:
              -
                type: text
                text: 'User-based pricing'
      -
        type: listItem
        content:
          -
            type: paragraph
            content:
              -
                type: text
                text: 'Freemium plans with upgraded paid tiers'
      -
        type: listItem
        content:
          -
            type: paragraph
            content:
              -
                type: text
                text: 'Useage-based pricing'
      -
        type: listItem
        content:
          -
            type: paragraph
            content:
              -
                type: text
                text: 'Custom-built failed-payment handling'
      -
        type: listItem
        content:
          -
            type: paragraph
            content:
              -
                type: text
                text: 'You name it...'
  -
    type: paragraph
    content:
      -
        type: text
        text: "We've also built selling features using "
      -
        type: text
        marks:
          -
            type: link
            attrs:
              href: 'https://stripe.com/connect'
              rel: null
              target: _blank
              title: null
        text: 'Stripe Connect'
      -
        type: text
        text: ", where customers can connect their own Stripe account and sell products and services through the platforms we've built."
  -
    type: paragraph
    content:
      -
        type: text
        text: "Overall, we've found the capabilities and API support that the Stripe platform has to offer to be just the tool for the job in basically every project we've been involved with."
