title: 'Product Management'
headline: 'Product Management Service'
sub_headline: 'Hire us as a fractional product manager for the build, launch, or lifecycle of your product.'
content:
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Product management is actually the bulk of the time we spend when developing, launching, and growing a software product.'
  -
    type: paragraph
    content:
      -
        type: text
        text: "It comes down to this simple truth:  If we're not building the right features, in the right priority order, for the right business goals, then the product will stagnate.  That's how we see our role as product manager."
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Brian has served as product manager on every product to date.  That includes deep customer research to understand the core job-to-be-done for a product or feature.  It flows into the design and development cycles where scoping in great detail becomes our unfair advantage, enabling us to move fast.'
updated_by: d5ab20b3-388d-4650-bb43-d170de415ebf
updated_at: 1709681528
