tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: project_logo_square
            field:
              mode: list
              container: assets
              restrict: true
              allow_uploads: true
              show_filename: true
              show_set_alt: true
              type: assets
              display: 'Project Square Logo'
              icon: assets
              instructions: 'Shown on project listing.  It should be a square SVG.'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              folder: images/projects/project_logos
          -
            handle: project_logo_full
            field:
              mode: list
              container: assets
              restrict: true
              allow_uploads: true
              show_filename: true
              show_set_alt: true
              type: assets
              display: 'Project Full Logo'
              icon: assets
              instructions: 'Shown on project single view.  It can be the full (rectangular) logo.  Should be an SVG.'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              folder: images/projects/project_logos
          -
            handle: logo_as_title
            field:
              default: false
              type: toggle
              display: 'Show the logo as the page title'
              icon: toggle
              instructions: 'Set this to true if the full logo should be displayed in place of the text title (as H1) on the single project page.'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: sub_headline
            field:
              input_type: text
              antlers: false
              type: text
              display: 'Sub Headline'
              icon: text
              instructions: '1 sentence to describe this project.  Shown on the index page and on the single project page.'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            import: bard_with_custom_components
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
          -
            handle: parent
            field:
              type: entries
              collections:
                - projects
              max_items: 1
              listable: false
              localizable: true
          -
            handle: featured_video
            field:
              type: video
              display: 'Featured Video'
              icon: video
              instructions: "Shown at the top of the single project view.  If set, then the featured image won't be shown."
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: featured_image
            field:
              mode: list
              container: assets
              restrict: true
              allow_uploads: true
              show_filename: true
              show_set_alt: true
              type: assets
              display: 'Featured Image'
              icon: assets
              instructions: 'Shown at the top of a single project view (unless a featured video is set).  It should be 1200x768.'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              folder: images/projects/project_images
          -
            handle: project_status
            field:
              input_type: text
              antlers: false
              type: text
              display: 'Project Status'
              icon: text
              instructions: 'A short sentence to specify the current status of this project.'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: website_url
            field:
              input_type: text
              placeholder: 'https://'
              antlers: false
              type: text
              display: 'Website URL'
              icon: text
              instructions: 'Enter the full website URL (including https://)'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: launched_date
            field:
              mode: single
              inline: false
              full_width: false
              columns: 1
              rows: 1
              time_enabled: false
              time_seconds_enabled: false
              type: date
              display: 'Launched Date'
              icon: date
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: technologies
            field:
              type: terms
              taxonomies:
                - technologies
              display: Technologies
              mode: select
          -
            handle: skills
            field:
              type: terms
              taxonomies:
                - skills
              display: Skills
              mode: select
  SEO:
    display: SEO
    sections:
      -
        fields:
          -
            handle: seo
            field:
              type: seo_pro
              listable: false
              display: SEO
title: Project
